### ISSUE TITLE
The world model is damaged after exporting to onnx

### ISSUE THREAD

**Issue by Pevernow** [Dan-wanna-M/rwkv-tensorrt#2]
with fp16 and version 17.

After exporting the model, attempting to use onnx infering resulted in an error.

onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from RWKV_32_4096_16_17_seq.onnx failed:Type Error: Type parameter (T) of Optype (Mul) bound to different types (tensor(float) and tensor(float16) in node ().

There seems to be a defect in fp16 quantification. Please fix it as soon as possible. Thank you

**Comment by Dan-wanna-M** [comment]
Onnx conversion development is now moved to https://github.com/daquexian/faster-rwkv. You can contact that author.
